spring: 
  profiles:
    active:
    - dev
---
server:
  port: 2004
  servlet :
    context-path: /
spring:
  profiles: dev
eureka: 
  instance:
    hostname: eureka2004.zrh.org
  client: 
    register-with-eureka: false     #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: false     #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url: 
       defaultZone: http://eureka2005.zrh.org:2005/eureka/,http://eureka2001.zrh.org:2001/eureka/,http://eureka2002.zrh.org:2002/eureka/,http://eureka2003.zrh.org:2003/eureka/       #设置与Eureka注册中心交互的地址，查询服务和注册服务用到       #设置与Eureka注册中心交互的地址，查询服务和注册服务用到
---
server:
  port: 2004
  servlet: 
    context-path: /
spring:
  profiles: test  
eureka: 
  instance:
    hostname: eureka2004.zrh.org
  client: 
    register-with-eureka: false     #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: false     #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url: 
       defaultZone: http://eureka2005.zrh.org:8888/eureka/,http://eureka2001.zrh.org:2001/eureka/,http://eureka2002.zrh.org:2002/eureka/,http://eureka2003.zrh.org:2003/eureka/        #设置与Eureka注册中心交互的地址，查询服务和注册服务用到       #设置与Eureka注册中心交互的地址，查询服务和注册服务用到
