spring: 
  profiles:
    active:
    - dev
---
server: 
  port: 1004
  servlet: 
    context-path: /
spring: 
  profiles: dev
  application:
    name: springcloud-student #then PRE_HOST in customer controller turn into http://springcloud-student 
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver #驱动
    url: jdbc:mysql://localhost:3306/db_springcloud?serverTimezone=UTC
    username: root
    password: 123456
  jpa: 
    hibernate: 
      ddl-auto: update 
    show-sql: true 
  thymeleaf: 
    cache: false 
eureka: 
  instance: 
    hostname: localhost
    appname: springcloud-student 
    instance-id: springcloud-student:1003 
    prefer-ip-address: true 
  client: 
    serviceUrl: 
      defaultZone: http://eureka2001.zrh.org:2001/eureka/,http://eureka2002.zrh.org:2002/eureka/,http://eureka2003.zrh.org:2003/eureka/,http://eureka2004.zrh.org:2004/eureka/ 
      #single eureka: http://localhost:2001/eureka 
info:
  groupId: $project.groupId$
  artifactId: $project.artifactId$
  version: $project.version$
  person in charge: zhongruihong
  tel: 15828095569
  provider: 1004
